
export const StatActions = {
    LOAD_FREE_CHAMPIONS_SUCCESS: 'LOAD_FREE_CHAMPIONS_SUCCESS',
    LOAD_FREE_CHAMPIONS_FAIL:'LOAD_FREE_CHAMPIONS_FAIL',
    LOAD_FREE_CHAMPIONS:'LOAD_FREE_CHAMPIONS',

    LOAD_SUMMONER_MASTERY:'LOAD_CHAMPION_MASTERY',
    LOAD_SUMMONER_MASTERY_SUCCESS:'LOAD_CHAMPION_MASTERY_SUCCESS',
    LOAD_SUMMONER_MASTERY_FAIL:'LOAD_CHAMPION_MASTERY_FAIL',
};